# Generated by Django 5.2.8 on 2025-12-15 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Egypt', max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days_min', models.PositiveIntegerField()),
                ('estimated_days_max', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_types',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='Customer order ID', max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in cm', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in cm', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=10)),
                ('content_description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('label_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, help_text='Assigned carrier for this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_shipments', to=settings.AUTH_USER_MODEL)),
                ('receiver_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_shipments', to='shipments.address')),
                ('sender_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_shipments', to='shipments.address')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.servicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User (carrier/admin) who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipments.shipment')),
            ],
            options={
                'db_table': 'tracking_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('event', models.CharField(choices=[('shipment.status_changed', 'Shipment Status Changed'), ('shipment.created', 'Shipment Created'), ('shipment.delivered', 'Shipment Delivered')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('secret', models.CharField(blank=True, help_text='Secret for webhook signature', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhooks',
                'unique_together': {('user', 'url', 'event')},
            },
        ),
    ]
