# Generated by Django 5.2.8 on 2025-12-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_id_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('1', 'Cairo'), ('2', 'Alexandria'), ('3', 'Kafr El Sheikh'), ('4', 'Dakahleya'), ('5', 'Sharkeya'), ('6', 'Gharbeya'), ('7', 'Monefeya'), ('8', 'Qalyubia'), ('9', 'Giza'), ('10', 'Bani-Sweif'), ('11', 'Fayoum'), ('12', 'Menya'), ('13', 'Assiut'), ('14', 'Sohag'), ('15', 'Qena'), ('16', 'Luxor'), ('17', 'Aswan'), ('18', 'Red Sea'), ('19', 'Behera'), ('20', 'Ismailia'), ('21', 'Suez'), ('22', 'Port-Said'), ('23', 'Damietta'), ('24', 'Marsa Matrouh'), ('25', 'Al-Wadi Al-Gadid'), ('26', 'North Sinai'), ('27', 'South Sinai')], max_length=50),
        ),
    ]
