# Generated by Django 5.2.8 on 2025-12-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
