# Generated by Django 5.2.8 on 2026-01-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_sent', models.JSONField(blank=True, help_text='The JSON payload sent to the webhook', null=True)),
                ('sending_status', models.CharField(blank=True, choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], help_text='Whether the attempt was successful', max_length=20, null=True)),
                ('response_info', models.JSONField(blank=True, help_text='Response from the server (status code, body, etc.)', null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_logs', to='shipments.webhook')),
            ],
            options={
                'db_table': 'sent_webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
