# Generated by Django 5.2.8 on 2025-12-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('carrier', 'Carrier'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
