# Generated by Django 5.2.8 on 2025-12-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('carrier', 'Carrier'), ('admin', 'Admin'), ('staff', 'Staff')], default='admin', max_length=20),
        ),
    ]
